import { useState } from 'react';
import { ReportSidebar, SectionId } from '@/components/dashboard/ReportSidebar';
import { ReportHeader } from '@/components/dashboard/ReportHeader';
import { FindingsSummary } from '@/components/dashboard/FindingsSummary';
import { MutatedGenesSection } from '@/components/dashboard/MutatedGenesSection';
import { FusionGenesSection } from '@/components/dashboard/FusionGenesSection';
import { StructuralVariantsSection } from '@/components/dashboard/StructuralVariantsSection';
import { CNAlteredGenesSection } from '@/components/dashboard/CNAlteredGenesSection';
import { ImmuneMarkersSection } from '@/components/dashboard/ImmuneMarkersSection';
import { HRDGenesSection } from '@/components/dashboard/HRDGenesSection';
import { CancerGenesSection } from '@/components/dashboard/CancerGenesSection';
import { AddendumSection } from '@/components/dashboard/AddendumSection';
import { usePatientData } from '@/contexts/PatientDataContext';

const Index = () => {
  const { data } = usePatientData();
  const [activeSection, setActiveSection] = useState<SectionId>('findings-summary');

  const handleSectionChange = (section: SectionId) => {
    setActiveSection(section);
    const element = document.getElementById(section);
    element?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <ReportHeader />
      
      {/* Main content with sidebar */}
      <div className="flex flex-1 overflow-hidden">
        {/* Left sidebar navigation */}
        <ReportSidebar activeSection={activeSection} onSectionChange={handleSectionChange} />
        
        {/* Main content area */}
        <main id="report-content" className="flex-1 overflow-y-auto p-8 bg-background">
          <FindingsSummary />
          <MutatedGenesSection />
          <FusionGenesSection />
          <StructuralVariantsSection />
          <CNAlteredGenesSection />
          <ImmuneMarkersSection />
          <HRDGenesSection />
          <CancerGenesSection />
          <AddendumSection />
          
          {/* Footer */}
          <footer className="border-t border-border bg-card px-6 py-4 mt-8 rounded-lg">
            <div className="flex flex-col sm:flex-row items-center justify-between gap-2 text-sm text-muted-foreground">
              <p>
                Generated by <span className="font-medium text-foreground">RNAsum</span> • 
                Reference: {data.sampleInfo.referenceCohort}
              </p>
              <p className="font-mono text-xs">
                Analysis Date: {data.sampleInfo.analysisDate}
              </p>
            </div>
          </footer>
        </main>
      </div>
    </div>
  );
};

export default Index;
